#���ݿ����ӳ�
spring:
  datasource:
    url: jdbc:mysql://106.14.81.50:3306/eld_care?serverTimezone=GMT&characterEncoding=utf8&useSSL=false
    username: remote
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#�ر� Thymeleaf �Ļ��濪����������������
  thymeleaf:
    cache: false
#����thymeleafҳ��ı���
    encoding: UTF-8
    mode: HTML5
#����thymeleafҳ��ĺ�׺
    suffix : .html
#����thymeleafҳ��Ĵ洢·��
    prefix: classpath:/templates/
server:
  port: 9090

logging:
  level:
    com:
      eldcare:
        main:
          mapper : debug
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.eldcare.main.entity